// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGsjnb3sKTc3Ovr-YS1s-t2UiniB1Py7U',
    appId: '1:1059312799046:web:e3300885b2ced75c74e947',
    messagingSenderId: '1059312799046',
    projectId: 'fittamebs',
    authDomain: 'fittamebs.firebaseapp.com',
    storageBucket: 'fittamebs.firebasestorage.app',
    measurementId: 'G-BJQSEM272D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI12NvVHGgW5YGAz7nZhHz05VtBsiQKm4',
    appId: '1:1059312799046:android:063b44db1ae28ebb74e947',
    messagingSenderId: '1059312799046',
    projectId: 'fittamebs',
    storageBucket: 'fittamebs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDdheExYOkq5ZZfxWZFjK3e7CxZMCeC58',
    appId: '1:1059312799046:ios:a6d72c3607231d3774e947',
    messagingSenderId: '1059312799046',
    projectId: 'fittamebs',
    storageBucket: 'fittamebs.firebasestorage.app',
    iosBundleId: 'com.example.fitta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDdheExYOkq5ZZfxWZFjK3e7CxZMCeC58',
    appId: '1:1059312799046:ios:a6d72c3607231d3774e947',
    messagingSenderId: '1059312799046',
    projectId: 'fittamebs',
    storageBucket: 'fittamebs.firebasestorage.app',
    iosBundleId: 'com.example.fitta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGsjnb3sKTc3Ovr-YS1s-t2UiniB1Py7U',
    appId: '1:1059312799046:web:8ae62178abcd04f974e947',
    messagingSenderId: '1059312799046',
    projectId: 'fittamebs',
    authDomain: 'fittamebs.firebaseapp.com',
    storageBucket: 'fittamebs.firebasestorage.app',
    measurementId: 'G-37F6WY1FMG',
  );
}
